import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { assertAdmin, logAudit } from "@/lib/admin.server";
import {
  admissionIdSchema,
  classTeacherSchema,
  createAdmissionSchema,
  exeatSchema,
  studentLoginSchema,
  updateAdmissionSchema,
} from "@/lib/admissions.schemas";

const STUDENT_EMAIL_DOMAIN = "students.local";

function studentLoginEmail(admissionNumber: string) {
  return `${admissionNumber.toLowerCase().replace(/[^a-z0-9-]/g, "")}@${STUDENT_EMAIL_DOMAIN}`;
}

function tempPassword() {
  const chunk = () => Math.random().toString(36).slice(2, 6).toUpperCase();
  return `Sch-${chunk()}-${chunk()}`;
}

type AdmissionInput = ReturnType<typeof createAdmissionSchema.parse>;

function toRow(d: AdmissionInput) {
  return {
    student_name: d.studentName,
    dob: d.dob || null,
    place_of_birth: d.placeOfBirth || null,
    class_admitted: d.classAdmitted,
    previous_school: d.previousSchool || null,
    previous_class: d.previousClass || null,
    last_attendance: d.lastAttendance || null,
    reason_for_leaving: d.reasonForLeaving || null,
    disability_status: d.disabilityStatus || "No",
    disability_type: d.disabilityType || null,
    assistance_needed: d.assistanceNeeded || null,
    gender: d.gender || "Other",
    parent_name: d.parentName,
    relationship: d.relationship || null,
    parent_phone: d.parentPhone || null,
    alt_contact: d.altContact || null,
    hometown: d.hometown || null,
    hometown_district: d.hometownDistrict || null,
    residence: d.residence || null,
    residence_district: d.residenceDistrict || null,
    parent_email: d.parentEmail.trim().toLowerCase(),
    emergency_name: d.emergencyName || null,
    emergency_phone: d.emergencyPhone || null,
    emergency_relationship: d.emergencyRelationship || null,
    emergency_residence: d.emergencyResidence || null,
    emergency_residence_district: d.emergencyResidenceDistrict || null,
    address: d.address || null,
    city: d.city || null,
    community: d.community || null,
    digital_address: d.digitalAddress || null,
  };
}

/** Admin/staff: everything the Admissions module renders. */
export const getAdmissionsOverview = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const [admissions, teachers, exeat] = await Promise.all([
      context.supabase.from("admissions").select("*").order("created_at", { ascending: false }),
      context.supabase.from("class_teachers").select("*").order("class_name"),
      context.supabase.from("student_exeat").select("*").order("created_at", { ascending: false }),
    ]);
    const first = admissions.error ?? teachers.error ?? exeat.error;
    if (first) throw new Error(first.message);
    return {
      admissions: admissions.data ?? [],
      classTeachers: teachers.data ?? [],
      exeat: exeat.data ?? [],
    };
  });

/**
 * Admin: admit a student. This is the only place parent and student logins are
 * created — no child in the school means no parent account.
 *
 * Parent login  = parent email + password (admin issued, forced change).
 * Student login = the same parent email + the child's admission number.
 */
export const createAdmission = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => createAdmissionSchema.parse(d))
  .handler(async ({ data, context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const row = toRow(data);
    const parentEmail = row.parent_email;

    // 1. Admission record (admission number is generated by the database).
    const { data: admission, error } = await supabaseAdmin
      .from("admissions")
      .insert({ ...row, created_by: context.userId })
      .select("*")
      .single();
    if (error || !admission) throw new Error(error?.message ?? "Could not save the admission.");
    const admissionNumber = admission.admission_number as string;

    // 2. Parent account — reused when the parent already has a child enrolled.
    let parentPassword: string | null = null;
    const { data: existingParent } = await supabaseAdmin
      .from("profiles")
      .select("id")
      .eq("email", parentEmail)
      .maybeSingle();

    let parentId = existingParent?.id as string | undefined;
    if (!parentId) {
      parentPassword = tempPassword();
      const { data: created, error: parentError } = await supabaseAdmin.auth.admin.createUser({
        email: parentEmail,
        password: parentPassword,
        email_confirm: true,
        user_metadata: { full_name: row.parent_name },
      });
      if (parentError || !created.user) {
        await supabaseAdmin.from("admissions").delete().eq("id", admission.id);
        throw new Error(parentError?.message ?? "Could not create the parent login.");
      }
      parentId = created.user.id;
      await supabaseAdmin.from("profiles").insert({
        id: parentId,
        full_name: row.parent_name,
        email: parentEmail,
        role: "parent",
        access_level: "basic",
        status: "active",
        phone: row.parent_phone,
        force_password_change: true,
      });
      await supabaseAdmin.from("user_roles").insert({ user_id: parentId, role: "parent" });
    }

    // 3. Student account: parent email + admission number.
    const loginEmail = studentLoginEmail(admissionNumber);
    const { data: student, error: studentError } = await supabaseAdmin.auth.admin.createUser({
      email: loginEmail,
      password: admissionNumber,
      email_confirm: true,
      user_metadata: { full_name: row.student_name, parent_email: parentEmail },
    });
    if (studentError || !student.user) {
      await supabaseAdmin.from("admissions").delete().eq("id", admission.id);
      throw new Error(studentError?.message ?? "Could not create the student login.");
    }
    await supabaseAdmin.from("profiles").insert({
      id: student.user.id,
      full_name: row.student_name,
      email: loginEmail,
      role: "student",
      access_level: "basic",
      status: "active",
      gender: row.gender,
      class_name: row.class_admitted,
      admission_number: admissionNumber,
    });
    await supabaseAdmin.from("user_roles").insert({ user_id: student.user.id, role: "student" });

    await supabaseAdmin
      .from("admissions")
      .update({
        parent_profile_id: parentId,
        student_profile_id: student.user.id,
        student_login_email: loginEmail,
      })
      .eq("id", admission.id);

    await logAudit(context.supabase, context.userId, {
      action: "student_admitted",
      description: `Admitted ${row.student_name} (${admissionNumber}) into ${row.class_admitted}`,
      targetEmail: parentEmail,
      details: { admissionNumber, parentEmail },
    });

    return {
      id: admission.id as string,
      admissionNumber,
      parentEmail,
      parentPassword,
      studentPassword: admissionNumber,
    };
  });

/** Admin: update an admission record. */
export const updateAdmission = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => updateAdmissionSchema.parse(d))
  .handler(async ({ data, context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const row = toRow(data);
    const { data: current } = await supabaseAdmin
      .from("admissions")
      .select("student_profile_id, admission_number")
      .eq("id", data.id)
      .maybeSingle();

    const { error } = await supabaseAdmin
      .from("admissions")
      .update({ ...row, status: data.status ?? "admitted" })
      .eq("id", data.id);
    if (error) throw new Error(error.message);

    if (current?.student_profile_id) {
      await supabaseAdmin
        .from("profiles")
        .update({
          full_name: row.student_name,
          class_name: row.class_admitted,
          gender: row.gender,
        })
        .eq("id", current.student_profile_id);
    }

    await logAudit(context.supabase, context.userId, {
      action: "admission_updated",
      description: `Updated admission ${current?.admission_number ?? data.id}`,
      targetEmail: row.parent_email,
    });
    return { ok: true };
  });

/** Admin: remove an admission and the student login attached to it. */
export const deleteAdmission = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => admissionIdSchema.parse(d))
  .handler(async ({ data, context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: row } = await supabaseAdmin
      .from("admissions")
      .select("student_profile_id, parent_profile_id, admission_number, parent_email")
      .eq("id", data.id)
      .maybeSingle();

    await supabaseAdmin.from("admissions").delete().eq("id", data.id);
    if (row?.student_profile_id) {
      await supabaseAdmin.from("profiles").delete().eq("id", row.student_profile_id);
      await supabaseAdmin.auth.admin.deleteUser(row.student_profile_id);
    }
    // A parent with no remaining children has no reason to hold an account.
    if (row?.parent_profile_id) {
      const { count } = await supabaseAdmin
        .from("admissions")
        .select("id", { count: "exact", head: true })
        .eq("parent_profile_id", row.parent_profile_id);
      if ((count ?? 0) === 0) {
        await supabaseAdmin.from("profiles").delete().eq("id", row.parent_profile_id);
        await supabaseAdmin.auth.admin.deleteUser(row.parent_profile_id);
      }
    }

    await logAudit(context.supabase, context.userId, {
      action: "admission_deleted",
      description: `Deleted admission ${row?.admission_number ?? data.id}`,
      targetEmail: row?.parent_email ?? null,
    });
    return { ok: true };
  });

/** Admin: assign the class teacher shown on the parent dashboard. */
export const saveClassTeacher = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => classTeacherSchema.parse(d))
  .handler(async ({ data, context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { error } = await context.supabase.from("class_teachers").upsert(
      {
        class_name: data.className,
        teacher_name: data.teacherName,
        teacher_email: data.teacherEmail,
        teacher_phone: data.teacherPhone,
      },
      { onConflict: "class_name" },
    );
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/** Staff/admin: record or clear an exeat (temporary permission to leave school). */
export const recordExeat = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => exeatSchema.parse(d))
  .handler(async ({ data, context }) => {
    const { data: actor } = await context.supabase
      .from("profiles")
      .select("full_name")
      .eq("id", context.userId)
      .maybeSingle();

    const { error } = await context.supabase.from("student_exeat").insert({
      admission_id: data.admissionId,
      status: data.status,
      reason: data.reason,
      destination: data.destination,
      signed_by_name: actor?.full_name ?? "",
      signed_by_id: context.userId,
      departed_at: data.status === "out" ? new Date().toISOString() : null,
      return_at: data.returnAt || null,
      returned_at: data.status === "in_school" ? new Date().toISOString() : null,
    });
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/**
 * Public: translate a student login (parent email + admission number) into the
 * internal login identity. It never reveals whether either value exists.
 */
export const resolveStudentLogin = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => studentLoginSchema.parse(d))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: row } = await supabaseAdmin
      .from("admissions")
      .select("student_login_email")
      .eq("parent_email", data.parentEmail.trim().toLowerCase())
      .eq("admission_number", data.admissionNumber.trim().toUpperCase())
      .maybeSingle();
    if (!row?.student_login_email) {
      throw new Error("No student matches that parent email and admission number.");
    }
    return { email: row.student_login_email as string };
  });

/** Parent: every child admitted under this parent's email, with class teacher. */
export const getMyChildren = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { data: children, error } = await context.supabase
      .from("admissions")
      .select(
        "id, admission_number, student_name, class_admitted, gender, dob, status, parent_email",
      )
      .order("created_at", { ascending: false });
    if (error) throw new Error(error.message);
    const rows = children ?? [];

    const { data: teachers } = await context.supabase.from("class_teachers").select("*");
    const byClass = new Map((teachers ?? []).map((t) => [t.class_name, t]));

    return rows.map((c) => ({
      ...c,
      teacher: byClass.get(c.class_admitted) ?? null,
    }));
  });

/** Parent/student: the full record for one child. */
export const getChildDetail = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => admissionIdSchema.parse(d))
  .handler(async ({ data, context }) => {
    const { supabase } = context;
    const { data: admission, error } = await supabase
      .from("admissions")
      .select("*")
      .eq("id", data.id)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!admission) throw new Error("Record not found.");

    const [performance, attendance, fees, exeat, teacher] = await Promise.all([
      supabase
        .from("student_performance")
        .select("*")
        .eq("admission_id", data.id)
        .order("recorded_at", { ascending: false }),
      supabase
        .from("student_attendance")
        .select("*")
        .eq("admission_id", data.id)
        .order("attendance_date", { ascending: false })
        .limit(120),
      supabase.from("student_fees").select("*").eq("admission_id", data.id).order("term"),
      supabase
        .from("student_exeat")
        .select("*")
        .eq("admission_id", data.id)
        .order("created_at", { ascending: false })
        .limit(20),
      supabase
        .from("class_teachers")
        .select("*")
        .eq("class_name", admission.class_admitted)
        .maybeSingle(),
    ]);

    return {
      admission,
      teacher: teacher.data ?? null,
      performance: performance.data ?? [],
      attendance: attendance.data ?? [],
      fees: fees.data ?? [],
      exeat: exeat.data ?? [],
    };
  });
