/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalModuleIdRouteImport } from './routes/_authenticated/portal.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalModuleIdRoute =
  AuthenticatedPortalModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/$moduleId': typeof AuthenticatedPortalModuleIdRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/portal/$moduleId': typeof AuthenticatedPortalModuleIdRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/portal/$moduleId': typeof AuthenticatedPortalModuleIdRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setup' | '/portal' | '/portal/$moduleId' | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setup' | '/portal/$moduleId' | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/setup'
    | '/_authenticated/portal'
    | '/_authenticated/portal/$moduleId'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/$moduleId': {
      id: '/_authenticated/portal/$moduleId'
      path: '/$moduleId'
      fullPath: '/portal/$moduleId'
      preLoaderRoute: typeof AuthenticatedPortalModuleIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalModuleIdRoute: typeof AuthenticatedPortalModuleIdRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalModuleIdRoute: AuthenticatedPortalModuleIdRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
